 #+BEGIN_SRC bash
               ,,
MMP""MM""YMM `7MM
P'   MM   `7   MM
     MM        MMpMMMb.  .gP"Ya
     MM        MM    MM ,M'   Yb
     MM        MM    MM 8M""""""
     MM        MM    MM YM.    ,
   .JMML.    .JMML  JMML.`Mbmmd'



                                                            ,,             ,,
MMP""MM""YMM                                         mm     db           `7MM
P'   MM   `7                                         MM                    MM
     MM  ,pW"Wq.`7Mb,od8 `7Mb,od8 .gP"Ya `7MMpMMMb.mmMMmm `7MM   ,6"Yb.    MM
     MM 6W'   `Wb MM' "'   MM' "',M'   Yb  MM    MM  MM     MM  8)   MM    MM
     MM 8M     M8 MM       MM    8M""""""  MM    MM  MM     MM   ,pm9MM    MM
     MM YA.   ,A9 MM       MM    YM.    ,  MM    MM  MM     MM  8M   MM    MM
   .JMML.`Ybmd9'.JMML.   .JMML.   `Mbmmd'.JMML  JMML.`Mbmo.JMML.`Moo9^Yo..JMML.



             ,,
MMP""MM""YMM db
P'   MM   `7
     MM    `7MM  `7MMpMMMb.pMMMb.  .gP"Ya  ,pP"Ybd
     MM      MM    MM    MM    MM ,M'   Yb 8I   `"
     MM      MM    MM    MM    MM 8M"""""" `YMMMa.
     MM      MM    MM    MM    MM YM.    , L.   I8
   .JMML.  .JMML..JMML  JMML  JMML.`Mbmmd' M9mmmP'

 #+END_SRC

* Concept
A reader-curated newspaper that rewards honest reporting and penalizes dishonest reporting

The problem of fake news may best be remedied by creating and popularizing decentralized news streams.  If today's prominent news organizations were stripped of their status as de-facto arbiters and messengers of truth,
we might be able to see them as the mere vestiges of 20th century business they are - unsustainable in their prioritization of profit and vulnerable to replacement by better models.  Like traditional media
organizations before Facebook, traditional hotels before AirBnB, or traditional Taxi companies before Uber, news organizations are operating under the illusion that they control
the sole infrastructure necessary to provide the services they offer.  That this wasn't the case in the above named industries became apparent only after platform businesses came along and gave
consumers a way of offering their own goods and services to meet each other's needs.  Now, consumers are becoming privy to the value that may be offered by their peers.  This is happening across all industries.

Now it's time for news to join the crowd (and the crowd to join news).

The Torrential Times is a proposal to revolutionize the news industry by taking editorial control out of the hands of a centralized few and using the intelligence of crowds to produce news that
does what it is meant to do: inform the public concerning the most important matters of our times.  What this requires is that the news-worthiness and truthfulness of news-content
won't be determined by small numbers of profit-motivated individuals whose interests are at odds with those of the majority of humanity.  Rather, crowd consensus will determine the news.

* Implementation
The key to achieving this concensus is by leveraging individual self-interest.  Below, we'll consider different steps that can be taken in this direction.  Each step will a way of further improving the integrity of the news-stream by expanding the readership while incentivizing its faithful contribution.

First, let's consider what decentralized news might look like without any substantive (monetary) incentive for its production and consumption (beyond lofty ideals like journalistic integrity, service to the public, etc.  Not to knock these, but they are only motivational to some and we are looking to inspire crowd-behavior...)

** Step 1: Reddit-Style Voting
Target Audience: "Real News" seekers

Imagine a news site seeking to fulfill much of what has been discussed above by being completely reader-curated, while relying on reader ratings to judge veracity of content.  All registered
readers can make posts containing a link and a headline summarizing the link.  These posts are meant to be upvoted or downvoted based on how truthful or misleading they are respectively.

As it stands, some problems become apparent with this approach:
1) What's preventing waves of contrarian readers from intentionally posting and upvoting misleading content?
2) Why should anyone consider this site's contents as news, when it's clearly just a message board taking itself too seriously?  Is anyone's job on the line if they post crap content?

Such a site would offer nothing new and be unlikely to attract many visitors.

** Step 2: Putting Money Where Mouths Are
Target Audience: same as level one, plus those hoping to make a profit by contributing "Real News"

Now add to this site a digital credit system.  Users load credit to their accounts and are told they will be paid for their reporting.  There is one important consideration: if they post misleading content,
they will be fined, and money will be deducted from their account.  Whether content is credible or misleading will be judged exactly as in Step 1 -- by users' votes -- but with the addition of real funds depending on these votes.  Posting content is taking a real risk, but with possible reward.  If a user posts a truthful article that is not easily debunkable,
they can expect to receive upvotes, for which they will be paid from a reserve.  On the other hand, bad content will receive downvotes, which deducts from the poster's account and goes into the
reserve.

What can ensure that upvotes/downvotes are faithful?  By similarly making the act of voting grounds for profit or loss.  If a user sees an article/headline that they suspect may be truthful, but they are ideologically
opposed to nonetheless and therefore decide to downvote, they would be foolish not to expect many others fact-checking for profit to subsequently upvote it and make them forfeit their bet.  Voting is like betting in that
it is a prediction of how the crowd will react to a particular piece of news.  Faithless voting is therefore self-sabotage, and can only take money out of the pockets of the deceitful.

The profit motive would suggest that this would attract more users than Step 1 alone, but there is still more that can be done to this end...

** Step 3: Attracting Outside Viewers through Classifieds Feature

Target Audience: same as layers one and two, plus outside parties hoping to use the platform to find or make offers

For many, the most important section of the newspaper is the classifieds.  Put classifieds on steroids and you have something like Craigslist - a service
very much in the spirit of what newspapers have always offered, but eminently useful and able to attract a wider audience than most newspapers through the effective use of
technology.

To introduce this feature into Torrential Times would be an easy way of growing the user-base so that the news being generated receives more oversight and readers.

** Step 4: Improving on Classifieds with Smart Contracts

Target Audience: same as layers one through three, plus future consumers of nascent value stored in the sharing economy

Craigslist was founded in 1995.  Since then, new technologies have been innovated that could offer as significant an improvement over Craigslist at it was over conventional classifieds sections of newspapers at the time.

What comes to mind is Blockchain - the distributed ledger technology first pioneered through Bitcoin.  Platforms based on Blockchain like Ethereum enable smart contracts, which make it possible to programatically add conditions
to business transactions, e.g. Alice will transfer X BTC/USD/EUR to Bob on the Condition that Bob sends her Y kilowatt-hours of solar energy.  This may sound implausible today, but if companies like Brooklyn Microgrid develop
simple ways to create local microgrids as they have in Brooklyn, a listing service that also acts as an escrow could help these solutions achieve widespread adoption -- solely through leveraging self interest.

An advanced integration of an offer-listing service with Blockchain could produce a platform offering services equivalent to (or better than) many those of many popular platforms.  Below we consider conceivable use-cases.


* Desired Outcomes
** Relevant News Reaching a General Audience
This is the primary goal.  According to this scheme, it is more attainable as the user-base grows, and the user-base primarily grows along with the usefulness of the newspaper.
** More Informed Consumers <==> Decentralization of Resources
Readers will notice that the products/services listed below are already being changed by platform businesses/the Sharing Economy/Post-Capitalism -- so what good would one more platform do?  Two things come to mind:
- 1) Businesses like AirBnB, Uber, etc take a huge cut for offering what amounts to nothing but information (from the client's POV).  If a viable alternative offered equivalent services but decided from the get-go to be as consumer-friendly as possible (i.e. take as small of a cut as possible or become a non-profit), it would have a chance at becoming very popular.  Successfully replicating even one of these services may produce this outcome.
- 2) Separate platforms exist across several industries where one effective platform, capitalizing on the similarity of infrastructure requirements, could feasibly subsume them all.  Remember, these are apps that companies offer - not physical infrastructures, which are provided by the customers.  The added benefit of consolidating these services would be that those who come to the platform to take advantage of a particular service will then be exposed to the other services offered.  The whole is greater than the sum of its parts.

* Contribute

contact mesh.dapp@gmail.com
